/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.*;
import training.*;

/**
 *
 * @author PSD-DANNY
 */
public class QuestionViewGrid extends javax.swing.JFrame {

    /**
     * Creates new form QuestionViewGrid
     */
    public DefaultTableModel model;
    int i = 1;
    private int selectedRow = 0;
    private Question q = new Question();

    public QuestionViewGrid() {
        initComponents();
        InitializeGrid();
        this.setTitle("Exam Questions");
    }

    public void updateModifications() {
        model.fireTableDataChanged();
    }

    private void InitializeGrid() {
        model = new DefaultTableModel();
        tblQuestions.setModel(model);

        model.addColumn("Question ID");
        model.addColumn("Question");
        model.addColumn("Option 1");
        model.addColumn("Option 2");
        model.addColumn("Option 3");
        model.addColumn("Option 4");
        model.addColumn("Answer");
        //hide the column Answer
        //tblQuestions.removeColumn(tblQuestions.getColumnModel().getColumn(6));
        Questions xmlObject = Training.jaxbXMLToObject();
        Training.itilQuestions = xmlObject;
        List<Question> qs = new ArrayList(xmlObject.getQuestions());
        //qs = xmlObject.getQuestions();
        qs.stream().forEach((a) -> {
            model.addRow(new Object[]{a.getQID(), a.getQuestion(), "Op1", "Op2", "Op3", "Op4", a.getAnswer()});
        });
        ListSelectionModel selectionModel = tblQuestions.getSelectionModel();
        selectionModel.setSelectionInterval(selectedRow, selectedRow);
        //ListSelectionModel model = table.getSelectionModel();
//        tblQuestions.setCellSelectionEnabled(false);
//        tblQuestions.setRowSelectionAllowed(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuestions = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnGenerateXML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ViewGrid"); // NOI18N

        tblQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblQuestions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuestionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuestions);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnGenerateXML.setText("Generate XML");
        btnGenerateXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(btnGenerateXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnGenerateXML)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        view.QuestionView1 qv = new view.QuestionView1(model);
        qv.setVisible(true);
        i++;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //model.removeRow(tblQuestions.getSelectedRow());
        JOptionPane.showMessageDialog(null, selectedRow);
        Questions xmlObject = Training.itilQuestions;
        List<Question> question = new ArrayList(xmlObject.getQuestions());
        for (Question b: question){
            if (b.getQID().equals("")) {
                
            }
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //JOptionPane.showMessageDialog(null, "Edit Window");
        QuestionView1 qv = new QuestionView1();
        qv.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnGenerateXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateXMLActionPerformed
        Questions qObject = new Questions();
        qObject = Training.itilQuestions;
        Training.jaxbObjectToXML(qObject);
    }//GEN-LAST:event_btnGenerateXMLActionPerformed

    private void tblQuestionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuestionsMouseClicked
        //if (evt.getClickCount() == 2) {
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();
        selectedRow = row;
        //JOptionPane.showMessageDialog(null, row);
        //}
    }//GEN-LAST:event_tblQuestionsMouseClicked

    private Questions gridQuestions() {
        Questions ques = new Questions();
        List question = new ArrayList();
        for (int i = 0; i < tblQuestions.getRowCount(); i++) {
            String QID = tblQuestions.getModel().getValueAt(i, 0).toString();
            String Q1 = tblQuestions.getModel().getValueAt(i, 1).toString();
            String A1 = tblQuestions.getModel().getValueAt(i, 2).toString();
            q.setQID(QID);
            q.setAnswer(A1);
            q.setQuestion(Q1);
            question.add(q);
            JOptionPane.showMessageDialog(null, q);
        }
        ques.setQuestions(question);
        return ques;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionViewGrid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionViewGrid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionViewGrid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionViewGrid.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionViewGrid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGenerateXML;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQuestions;
    // End of variables declaration//GEN-END:variables
}
